boot {
	generate grub
	default "Funtoo Linux"
	timeout 3
}
"Funtoo Linux" {
	kernel kernel[-v]
	initrd initramfs[-v]
	params crypt_root=UUID=8dede5ea-0596-4e52-82d6-32381407276a 
	params += dolvm 
	params += real_root=/dev/mapper/fast-root 
	params += ro 
	params += rootfstype=f2fs 
	params += resume=swap:/dev/mapper/slow-swap
	params += keymap=dvorak 
#	params += quiet
}

