boot {
	generate grub
	default "Funtoo Linux"
	timeout 3
}
"Funtoo Linux" {
	kernel kernel[-v]
	initrd initramfs[-v]
	params += crypt_root=UUID=MJvkmi-D6PZ-h8T0-eVi7-2rZj-Y2ML-MZr0Y5 dolvm real_root=/dev/mapper/fast-root ro rootfstype=f2fs resume=swap:/dev/mapper/slow-swap #quiet
}

