boot {
	generate grub
	default "Funtoo Linux"
	timeout 3
}
"Funtoo Linux" {
	kernel kernel[-v]
	initrd initramfs[-v]
	params crypt_root=UUID=MJvkmi-D6PZ-h8T0-eVi7-2rZj-Y2ML-MZr0Y5 
	params += dolvm 
	params += real_root=/dev/mapper/fast-root 
	params += ro 
	params += rootfstype=f2fs 
	params += resume=swap:/dev/mapper/slow-swap 
#	params += quiet
}

