#tarballs count. default 10
#COUNT=""

#use '.*' instead '*' for wildcard patterns
#dont check following categories
#IGNORE_CATEGORY="cross-.*"

#dont check following packages names
#IGNORE_PN=""

# Directories to ignore in /etc/portage/
IGNORE_DIRS="package.env env binrepos.conf gnupg profile"

# File patterns to ignore
IGNORE_FILE_PATTERNS="zzz.*"

#default options. '-rc' Highly recommend!
PORTCONF_DEFAULT_OPTS="-b"
