# /etc/portconf.conf

# tarballs count. default 10
#COUNT="10"

# use '.*' instead '*' for wildcard patterns
# dont check following categories
#IGNORE_CATEGORY="cross-.*"

# dont check following packages names
# ex. dev-lang/php
# ex. dev-lang/php apache
#IGNORE_PN=""

# default options. '-rc' Highly recommend!
PORTCONF_DEFAULT_OPTS="-rc -ip"

# Ignoriere package.env und env/.d Checks (yes/no)
IGNORE_ENV_CHECKS="yes"

