COMMON_FLAGS="-march=x86-64-v2 -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="${RUSTFLAGS} -C target-cpu=x86-64-v2"

LC_MESSAGES=C.utf8

MAKEOPTS="-j45 -l12"

USE="-X zsh-completion vim-syntax offensive -ipv6 -doc -branding"

#FEATURES="ccache distcc" #set DISTCC_HOSTS="lianhua/4 mavis/16" in /etc/distcc

EMERGE_DEFAULT_OPTS="--jobs=24 --load-average=24 --binpkg-respect-use=y"

L10N="en-US en en-us"
LINGUAS="en_US"

GENTOO_MIRRORS="https://gentoo.osuosl.org/ http://gentoo.osuosl.org/ https://mirror.servaxnet.com/gentoo/ http://mirror.servaxnet.com/gentoo/ http://gentoo-mirror.flux.utah.edu/"
