MAKEOPTS="-j24 -l12"

FEATURES="distcc"

EMERGE_DEFAULT_OPTS="--job=6 --load-average=12 --binpkg-respect-use=y"

USE="zsh zsh-completion vim-syntax offensive -X -ipv6 offensive -doc -ipv6 -branding zsh-completion"
