add_dracutmodules+=" lvm nvme i18n rescue dm rootfs-block fstab-sys "

install_items+=" /lib/modules/$KERNEL_VERSION/kernel/drivers/nvme/host/nvme.ko /lib/modules/$KERNEL_VERSION/kernel/drivers/nvme/host/nvme-core.ko "

