# created by eselect-repo

[argent-main]
location = /var/db/repos/argent-main
sync-type = git
sync-uri = https://github.com/gentoo-mirror/argent-main.git

[jm-overlay]
location = /var/db/repos/jm-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/jm-overlay.git

[flow]
location = /var/db/repos/flow
sync-type = git
sync-uri = https://github.com/gentoo-mirror/flow.git
