
[gentoo]
location = /var/db/repos/gentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo.git


# created by eselect-repo

[kde]
location = /var/db/repos/kde
sync-type = git
sync-uri = https://anongit.gentoo.org/git/proj/kde.git


[nest]
location = /var/db/repos/nest
sync-type = git
sync-uri = https://github.com/SpiderX/portage-overlay.git

[spikyatlinux]
location = /var/db/repos/spikyatlinux
sync-type = git
sync-uri = https://github.com/spikyatlinux/ebuilds_for_gentoo.git

[flow]
location = /var/db/repos/flow
sync-type = git
sync-uri = https://gitlab.com/Flow/flow-s-ebuilds.git

[ace]
location = /var/db/repos/ace
sync-type = git
sync-uri = https://github.com/ananace/overlay.git

[robert7k]
location = /var/db/repos/robert7k
sync-type = git
sync-uri = https://github.com/robert7k/gentoo-overlay.git
