[src_prepare-overlay]
priority = 50
location = /var/lib/layman/src_prepare-overlay
layman-type = git
auto-sync = No

[flow]
priority = 50
location = /var/lib/layman/flow
layman-type = git
auto-sync = No

